/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCallbackRouteImport } from './routes/admin.callback'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as ArAlbumIdRouteImport } from './routes/ar.$albumId'
import { Route as AdminAlbumsIdIndexRouteImport } from './routes/admin.albums.$id.index'
import { Route as AdminAlbumsIdShareRouteImport } from './routes/admin.albums.$id.share'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallbackRoute = AdminCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const ArAlbumIdRoute = ArAlbumIdRouteImport.update({
  id: '/ar/$albumId',
  path: '/ar/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlbumsIdIndexRoute = AdminAlbumsIdIndexRouteImport.update({
  id: '/albums/$id/',
  path: '/albums/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlbumsIdShareRoute = AdminAlbumsIdShareRouteImport.update({
  id: '/albums/$id/share',
  path: '/albums/$id/share',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/ar/$albumId': typeof ArAlbumIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/albums/$id/share': typeof AdminAlbumsIdShareRoute
  '/admin/albums/$id/': typeof AdminAlbumsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/ar/$albumId': typeof ArAlbumIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/albums/$id/share': typeof AdminAlbumsIdShareRoute
  '/admin/albums/$id': typeof AdminAlbumsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/ar/$albumId': typeof ArAlbumIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/albums/$id/share': typeof AdminAlbumsIdShareRoute
  '/admin/albums/$id/': typeof AdminAlbumsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/callback'
    | '/admin/settings'
    | '/admin/upload'
    | '/ar/$albumId'
    | '/admin/'
    | '/admin/albums/$id/share'
    | '/admin/albums/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/callback'
    | '/admin/settings'
    | '/admin/upload'
    | '/ar/$albumId'
    | '/admin'
    | '/admin/albums/$id/share'
    | '/admin/albums/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/callback'
    | '/admin/settings'
    | '/admin/upload'
    | '/ar/$albumId'
    | '/admin/'
    | '/admin/albums/$id/share'
    | '/admin/albums/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArAlbumIdRoute: typeof ArAlbumIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/callback': {
      id: '/admin/callback'
      path: '/callback'
      fullPath: '/admin/callback'
      preLoaderRoute: typeof AdminCallbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ar/$albumId': {
      id: '/ar/$albumId'
      path: '/ar/$albumId'
      fullPath: '/ar/$albumId'
      preLoaderRoute: typeof ArAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/albums/$id/': {
      id: '/admin/albums/$id/'
      path: '/albums/$id'
      fullPath: '/admin/albums/$id/'
      preLoaderRoute: typeof AdminAlbumsIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/albums/$id/share': {
      id: '/admin/albums/$id/share'
      path: '/albums/$id/share'
      fullPath: '/admin/albums/$id/share'
      preLoaderRoute: typeof AdminAlbumsIdShareRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCallbackRoute: typeof AdminCallbackRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlbumsIdShareRoute: typeof AdminAlbumsIdShareRoute
  AdminAlbumsIdIndexRoute: typeof AdminAlbumsIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCallbackRoute: AdminCallbackRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAlbumsIdShareRoute: AdminAlbumsIdShareRoute,
  AdminAlbumsIdIndexRoute: AdminAlbumsIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArAlbumIdRoute: ArAlbumIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
